# Generated by Django 4.2.18 on 2025-01-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='email',
        ),
    ]
