# Generated by Django 4.2.18 on 2025-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_remove_employee_email_remove_individual_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=50)),
            ],
        ),
    ]
