# Generated by Django 4.2.18 on 2025-02-07 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_participant_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='organization_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Organization Email'),
        ),
    ]
