# Generated by Django 5.1.5 on 2025-02-05 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_participant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='guest_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization'),
        ),
    ]
