# Generated by Django 4.2.18 on 2025-01-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
