# Generated by Django 4.2.18 on 2025-02-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_participant_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='guest_name',
            field=models.CharField(max_length=255, verbose_name='Name*'),
        ),
    ]
