# Generated by Django 4.2.18 on 2025-02-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_participant_organization_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='organization_email',
        ),
    ]
