# Generated by Django 4.2.18 on 2025-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_rename_guest_email_participant_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='participant',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approve?'),
        ),
    ]
