# Generated by Django 5.1.5 on 2025-02-07 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_alter_participant_options_participant_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomStyleInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('greeting_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Greeting Title')),
                ('greeting_description', models.CharField(max_length=255, verbose_name='Greeting Description*')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('thank_you_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Thank You Image')),
                ('set_as_background', models.BooleanField(default=False, verbose_name='Set as Background Image?')),
                ('enable_dark_mode', models.BooleanField(default=False, verbose_name='Enable Dark Mode?')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invitation.event', verbose_name='Event')),
            ],
        ),
    ]
