# Generated by Django 4.2.18 on 2025-01-31 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0005_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Nama Tamu')),
                ('guest_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Tamu')),
                ('is_attending', models.BooleanField(default=False, verbose_name='Hadir?')),
                ('additional_guests', models.PositiveIntegerField(default=0, verbose_name='Tamu Tambahan')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Permintaan Khusus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitation.event', verbose_name='Undangan')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Instansi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat Instansi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Instansi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon Instansi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='guest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation.organization', verbose_name='Instansi'),
        ),
    ]
