# Generated by Django 5.1.5 on 2025-02-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0006_customstyleinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstyleinvitation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='invitation.event', verbose_name='Event'),
        ),
    ]
