# Generated by Django 4.2.18 on 2025-02-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_event_event_name_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='from_event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AddField(
            model_name='event',
            name='maps_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='to_event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
