# Generated by Django 5.1.5 on 2025-02-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0007_alter_customstyleinvitation_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomStyleInvitation',
            new_name='StyleInvitation',
        ),
    ]
