# Generated by Django 4.2.18 on 2025-02-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0008_rename_event_date_event_from_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to_event_date',
            field=models.DateTimeField(),
        ),
    ]
