# Generated by Django 5.1.5 on 2025-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_rename_styleinvitation_invitationstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationstyle',
            name='greeting_title',
            field=models.CharField(max_length=255, verbose_name='Greeting Title'),
        ),
    ]
