# Generated by Django 4.2.18 on 2025-02-03 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0009_alter_event_to_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
