# Generated by Django 5.1.5 on 2025-02-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_alter_invitationstyle_greeting_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationstyle',
            old_name='thank_you_image',
            new_name='appreciation_image',
        ),
    ]
