# Generated by Django 4.2.18 on 2025-02-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0010_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
