# Generated by Django 5.1.5 on 2025-02-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0011_rename_thank_you_image_invitationstyle_appreciation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationstyle',
            name='set_as_background',
        ),
        migrations.AlterField(
            model_name='invitationstyle',
            name='greeting_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Greeting Description*'),
        ),
        migrations.AlterField(
            model_name='invitationstyle',
            name='greeting_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Greeting Title'),
        ),
    ]
