# Generated by Django 5.1.5 on 2025-02-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0012_remove_invitationstyle_set_as_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationstyle',
            name='appreciation_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Appreciation Text'),
        ),
        migrations.AlterField(
            model_name='invitationstyle',
            name='appreciation_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Appreciation Image'),
        ),
        migrations.AlterField(
            model_name='invitationstyle',
            name='greeting_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Greeting Description'),
        ),
    ]
