# Generated by Django 4.2.18 on 2025-02-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
