# Generated by Django 5.1.5 on 2025-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0013_invitationstyle_appreciation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_attending',
            field=models.BooleanField(default=False, verbose_name='Is attending'),
        ),
    ]
