# Generated by Django 4.2.19 on 2025-02-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0014_participant_attendance_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='Event Name*'),
        ),
        migrations.AlterField(
            model_name='event',
            name='maps_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maps location'),
        ),
    ]
