# Generated by Django 4.2.19 on 2025-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0015_alter_event_event_name_alter_event_maps_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(verbose_name='Location*'),
        ),
    ]
