# Generated by Django 4.2.19 on 2025-02-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0016_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='from_event_date',
            field=models.DateTimeField(verbose_name='From Event Date*'),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_event_date',
            field=models.DateTimeField(verbose_name='To Event Date*'),
        ),
    ]
