# Generated by Django 5.1.5 on 2025-02-04 13:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0018_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instansi')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Nama Tamu')),
                ('guest_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Tamu')),
                ('is_attending', models.BooleanField(default=False, verbose_name='Hadir?')),
                ('additional_guests', models.PositiveIntegerField(default=0, verbose_name='Tamu Tambahan')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Permintaan Khusus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitation.event', verbose_name='Undangan')),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
