# Generated by Django 4.2.19 on 2025-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0018_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maps_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maps Location URL'),
        ),
    ]
