# Generated by Django 4.2.18 on 2025-02-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0019_alter_event_maps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationstyle',
            name='disable_qr_code_invitation',
            field=models.BooleanField(default=False, verbose_name='Disable QR Code on Invitation?'),
        ),
    ]
