# Generated by Django 4.2.18 on 2025-02-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0020_invitationstyle_disable_qr_code_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationstyle',
            name='disable_qr_code_invitation',
        ),
        migrations.AddField(
            model_name='invitationstyle',
            name='show_map_qrcode_on_invitation',
            field=models.BooleanField(default=True, verbose_name='Show Maps QR Code on Invitation?'),
        ),
    ]
