# Generated by Django 4.2.18 on 2025-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0022_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Event Cover Image'),
        ),
    ]
