# Generated by Django 4.2.18 on 2025-02-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0024_event_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_link',
            field=models.CharField(max_length=10, unique=True, verbose_name='Short Link'),
        ),
    ]
