# Generated by Django 4.2.18 on 2025-02-13 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0029_alter_event_submitter_alter_participant_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
