# Generated by Django 5.1.6 on 2025-02-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0031_participant_is_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quota_limitation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
