# Generated by Django 4.2.18 on 2025-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0032_event_quota_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='quota_limitation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Participant Quota*'),
        ),
    ]
